# Uncomment this line to define a global platform for your project
# platform :ios, “7.0”

target "XiHaBearClientTests" do

pod 'AFNetworking', '~> 2.5.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'JSONModel', '~> 1.0.1'

end

